# NAICS Classification Configuration for MCP Server Embedding Analysis
# This file contains the NAICS sector definitions and keyword mappings for classifying MCP servers

# NAICS Sector Definitions
NAICS_SECTORS = {
    11: "Agriculture, Forestry, Fishing and Hunting",
    21: "Mining, Quarrying, and Oil and Gas Extraction",
    22: "Utilities",
    23: "Construction",
    31: "Manufacturing",
    42: "Wholesale Trade",
    44: "Retail Trade",
    48: "Transportation and Warehousing",
    51: "Information",
    52: "Finance and Insurance",
    53: "Real Estate and Rental and Leasing",
    54: "Professional, Scientific, and Technical Services",
    55: "Management of Companies and Enterprises",
    56: "Administrative and Support and Waste Management and Remediation Services",
    61: "Educational Services",
    62: "Health Care and Social Assistance",
    71: "Arts, Entertainment, and Recreation",
    72: "Accommodation and Food Services",
    81: "Other Services (except Public Administration)",
    92: "Public Administration",
    99: "Unclassified"
}

# NAICS 4-digit Subsector Definitions
NAICS_SUBSECTORS = {
    1111: "Oilseed and Grain Farming",
    1112: "Vegetable and Melon Farming",
    1113: "Fruit and Tree Nut Farming",
    1114: "Greenhouse, Nursery, and Floriculture Production",
    1119: "Other Crop Farming",
    1121: "Cattle Ranching and Farming",
    1122: "Hog and Pig Farming",
    1123: "Poultry and Egg Production",
    1124: "Sheep and Goat Farming",
    1125: "Aquaculture",
    1129: "Other Animal Production",
    1131: "Timber Tract Operations",
    1132: "Forest Nurseries and Gathering of Forest Products",
    1133: "Logging",
    1141: "Fishing",
    1142: "Hunting and Trapping",
    1151: "Support Activities for Crop Production",
    1152: "Support Activities for Animal Production",
    1153: "Support Activities for Forestry",
    2111: "Oil and Gas Extraction",
    2121: "Coal Mining",
    2122: "Metal Ore Mining",
    2123: "Nonmetallic Mineral Mining and Quarrying",
    2131: "Support Activities for Mining",
    2211: "Electric Power Generation, Transmission and Distribution",
    2212: "Natural Gas Distribution",
    2213: "Water, Sewage and Other Systems",
    2361: "Residential Building Construction",
    2362: "Nonresidential Building Construction",
    2371: "Utility System Construction",
    2372: "Land Subdivision",
    2373: "Highway, Street, and Bridge Construction",
    2379: "Other Heavy and Civil Engineering Construction",
    2381: "Foundation, Structure, and Building Exterior Contractors",
    2382: "Building Equipment Contractors",
    2383: "Building Finishing Contractors",
    2389: "Other Specialty Trade Contractors",
    3111: "Animal Food Manufacturing",
    3112: "Grain and Oilseed Milling",
    3113: "Sugar and Confectionery Product Manufacturing",
    3114: "Fruit and Vegetable Preserving and Specialty Food Manufacturing",
    3115: "Dairy Product Manufacturing",
    3116: "Animal Slaughtering and Processing",
    3117: "Seafood Product Preparation and Packaging",
    3118: "Bakeries and Tortilla Manufacturing",
    3119: "Other Food Manufacturing",
    3121: "Beverage Manufacturing",
    3122: "Tobacco Manufacturing",
    3131: "Fiber, Yarn, and Thread Mills",
    3132: "Fabric Mills",
    3133: "Textile and Fabric Finishing and Fabric Coating Mills",
    3141: "Textile Furnishings Mills",
    3149: "Other Textile Product Mills",
    3151: "Apparel Knitting Mills",
    3152: "Cut and Sew Apparel Manufacturing",
    3159: "Apparel Accessories and Other Apparel Manufacturing",
    3161: "Leather and Hide Tanning and Finishing",
    3162: "Footwear Manufacturing",
    3169: "Other Leather and Allied Product Manufacturing",
    3211: "Sawmills and Wood Preservation",
    3212: "Veneer, Plywood, and Engineered Wood Product Manufacturing",
    3219: "Other Wood Product Manufacturing",
    3221: "Pulp, Paper, and Paperboard Mills",
    3222: "Converted Paper Product Manufacturing",
    3231: "Printing and Related Support Activities",
    3241: "Petroleum and Coal Products Manufacturing",
    3251: "Basic Chemical Manufacturing",
    3252: "Resin, Synthetic Rubber, and Artificial and Synthetic Fibers and Filaments Manufacturing",
    3253: "Pesticide, Fertilizer, and Other Agricultural Chemical Manufacturing",
    3254: "Pharmaceutical and Medicine Manufacturing",
    3255: "Paint, Coating, and Adhesive Manufacturing",
    3256: "Soap, Cleaning Compound, and Toilet Preparation Manufacturing",
    3259: "Other Chemical Product and Preparation Manufacturing",
    3261: "Plastics Product Manufacturing",
    3262: "Rubber Product Manufacturing",
    3271: "Clay Product and Refractory Manufacturing",
    3272: "Glass and Glass Product Manufacturing",
    3273: "Cement and Concrete Product Manufacturing",
    3274: "Lime and Gypsum Product Manufacturing",
    3279: "Other Nonmetallic Mineral Product Manufacturing",
    3311: "Iron and Steel Mills and Ferroalloy Manufacturing",
    3312: "Steel Product Manufacturing from Purchased Steel",
    3313: "Alumina and Aluminum Production and Processing",
    3314: "Nonferrous Metal (except Aluminum) Production and Processing",
    3315: "Foundries",
    3321: "Forging and Stamping",
    3322: "Cutlery and Handtool Manufacturing",
    3323: "Architectural and Structural Metals Manufacturing",
    3324: "Boiler, Tank, and Shipping Container Manufacturing",
    3325: "Hardware Manufacturing",
    3326: "Spring and Wire Product Manufacturing",
    3327: "Machine Shops; Turned Product; and Screw, Nut, and Bolt Manufacturing",
    3328: "Coating, Engraving, Heat Treating, and Allied Activities",
    3329: "Other Fabricated Metal Product Manufacturing",
    3331: "Agriculture, Construction, and Mining Machinery Manufacturing",
    3332: "Industrial Machinery Manufacturing",
    3333: "Commercial and Service Industry Machinery Manufacturing",
    3334: "Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing",
    3335: "Metalworking Machinery Manufacturing",
    3336: "Engine, Turbine, and Power Transmission Equipment Manufacturing",
    3339: "Other General Purpose Machinery Manufacturing",
    3341: "Computer and Peripheral Equipment Manufacturing",
    3342: "Communications Equipment Manufacturing",
    3343: "Audio and Video Equipment Manufacturing",
    3344: "Semiconductor and Other Electronic Component Manufacturing",
    3345: "Navigational, Measuring, Electromedical, and Control Instruments Manufacturing",
    3346: "Manufacturing and Reproducing Magnetic and Optical Media",
    3351: "Electric Lighting Equipment Manufacturing",
    3352: "Household Appliance Manufacturing",
    3353: "Electrical Equipment Manufacturing",
    3359: "Other Electrical Equipment and Component Manufacturing",
    3361: "Motor Vehicle Manufacturing",
    3362: "Motor Vehicle Body and Trailer Manufacturing",
    3363: "Motor Vehicle Parts Manufacturing",
    3364: "Aerospace Product and Parts Manufacturing",
    3365: "Railroad Rolling Stock Manufacturing",
    3366: "Ship and Boat Building",
    3369: "Other Transportation Equipment Manufacturing",
    3371: "Household and Institutional Furniture and Kitchen Cabinet Manufacturing",
    3372: "Office Furniture (including Fixtures) Manufacturing",
    3379: "Other Furniture Related Product Manufacturing",
    3391: "Medical Equipment and Supplies Manufacturing",
    3399: "Other Miscellaneous Manufacturing",
    4231: "Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers",
    4232: "Furniture and Home Furnishing Merchant Wholesalers",
    4233: "Lumber and Other Construction Materials Merchant Wholesalers",
    4234: "Professional and Commercial Equipment and Supplies Merchant Wholesalers",
    4235: "Metal and Mineral (except Petroleum) Merchant Wholesalers",
    4236: "Household Appliances and Electrical and Electronic Goods Merchant Wholesalers",
    4237: "Hardware, and Plumbing and Heating Equipment and Supplies Merchant Wholesalers",
    4238: "Machinery, Equipment, and Supplies Merchant Wholesalers",
    4239: "Miscellaneous Durable Goods Merchant Wholesalers",
    4241: "Paper and Paper Product Merchant Wholesalers",
    4242: "Drugs and Druggists' Sundries Merchant Wholesalers",
    4243: "Apparel, Piece Goods, and Notions Merchant Wholesalers",
    4244: "Grocery and Related Product Merchant Wholesalers",
    4245: "Farm Product Raw Material Merchant Wholesalers",
    4246: "Chemical and Allied Products Merchant Wholesalers",
    4247: "Petroleum and Petroleum Products Merchant Wholesalers",
    4248: "Beer, Wine, and Distilled Alcoholic Beverage Merchant Wholesalers",
    4249: "Miscellaneous Nondurable Goods Merchant Wholesalers",
    4251: "Wholesale Trade Agents and Brokers",
    4411: "Automobile Dealers",
    4412: "Other Motor Vehicle Dealers",
    4413: "Automotive Parts, Accessories, and Tire Retailers",
    4441: "Building Material and Supplies Dealers",
    4442: "Lawn and Garden Equipment and Supplies Retailers",
    4451: "Grocery and Convenience Retailers",
    4452: "Specialty Food Retailers",
    4453: "Beer, Wine, and Liquor Retailers",
    4491: "Furniture and Home Furnishings Retailers",
    4492: "Electronics and Appliance Retailers",
    4551: "Department Stores",
    4552: "Warehouse Clubs, Supercenters, and Other General Merchandise Retailers",
    4561: "Health and Personal Care Retailers",
    4571: "Gasoline Stations",
    4572: "Fuel Dealers",
    4581: "Clothing and Clothing Accessories Retailers",
    4582: "Shoe Retailers",
    4583: "Jewelry, Luggage, and Leather Goods Retailers",
    4591: "Sporting Goods, Hobby, and Musical Instrument Retailers",
    4592: "Book Retailers and News Dealers",
    4593: "Florists",
    4594: "Office Supplies, Stationery, and Gift Retailers",
    4595: "Used Merchandise Retailers",
    4599: "Other Miscellaneous Retailers",
    4811: "Scheduled Air Transportation",
    4812: "Nonscheduled Air Transportation",
    4821: "Rail Transportation",
    4831: "Deep Sea, Coastal, and Great Lakes Water Transportation",
    4832: "Inland Water Transportation",
    4841: "General Freight Trucking",
    4842: "Specialized Freight Trucking",
    4851: "Urban Transit Systems",
    4852: "Interurban and Rural Bus Transportation",
    4853: "Taxi and Limousine Service",
    4854: "School and Employee Bus Transportation",
    4855: "Charter Bus Industry",
    4859: "Other Transit and Ground Passenger Transportation",
    4861: "Pipeline Transportation of Crude Oil",
    4862: "Pipeline Transportation of Natural Gas",
    4869: "Other Pipeline Transportation",
    4871: "Scenic and Sightseeing Transportation, Land",
    4872: "Scenic and Sightseeing Transportation, Water",
    4879: "Scenic and Sightseeing Transportation, Other",
    4881: "Support Activities for Air Transportation",
    4882: "Support Activities for Rail Transportation",
    4883: "Support Activities for Water Transportation",
    4884: "Support Activities for Road Transportation",
    4885: "Freight Transportation Arrangement",
    4889: "Other Support Activities for Transportation",
    4911: "Postal Service",
    4921: "Couriers and Express Delivery Services",
    4922: "Local Messengers and Local Delivery",
    4931: "Warehousing and Storage",
    5121: "Motion Picture and Video Industries",
    5122: "Sound Recording Industries",
    5131: "Newspaper, Periodical, Book, and Directory Publishers",
    5132: "Software Publishers",
    5161: "Radio and Television Broadcasting Stations",
    5162: "Media Streaming Distribution Services, Social Networks, and Other Media Networks and Content Providers",
    5171: "Wired and Wireless Telecommunications (except Satellite)",
    5174: "Satellite Telecommunications",
    5178: "All Other Telecommunications",
    5182: "Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services",
    5192: "Web Search Portals, Libraries, Archives, and Other Information Services",
    5211: "Monetary Authorities-Central Bank",
    5221: "Depository Credit Intermediation",
    5222: "Nondepository Credit Intermediation",
    5223: "Activities Related to Credit Intermediation",
    5231: "Securities and Commodity Contracts Intermediation and Brokerage",
    5232: "Securities and Commodity Exchanges",
    5239: "Other Financial Investment Activities",
    5241: "Insurance Carriers",
    5242: "Agencies, Brokerages, and Other Insurance Related Activities",
    5251: "Insurance and Employee Benefit Funds",
    5259: "Other Investment Pools and Funds",
    5311: "Lessors of Real Estate",
    5312: "Offices of Real Estate Agents and Brokers",
    5313: "Activities Related to Real Estate",
    5321: "Automotive Equipment Rental and Leasing",
    5322: "Consumer Goods Rental",
    5323: "General Rental Centers",
    5324: "Commercial and Industrial Machinery and Equipment Rental and Leasing",
    5331: "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)",
    5411: "Legal Services",
    5412: "Accounting, Tax Preparation, Bookkeeping, and Payroll Services",
    5413: "Architectural, Engineering, and Related Services",
    5414: "Specialized Design Services",
    5415: "Computer Systems Design and Related Services",
    5416: "Management, Scientific, and Technical Consulting Services",
    5417: "Scientific Research and Development Services",
    5418: "Advertising, Public Relations, and Related Services",
    5419: "Other Professional, Scientific, and Technical Services",
    5511: "Management of Companies and Enterprises",
    5611: "Office Administrative Services",
    5612: "Facilities Support Services",
    5613: "Employment Services",
    5614: "Business Support Services",
    5615: "Travel Arrangement and Reservation Services",
    5616: "Investigation and Security Services",
    5617: "Services to Buildings and Dwellings",
    5619: "Other Support Services",
    5621: "Waste Collection",
    5622: "Waste Treatment and Disposal",
    5629: "Remediation and Other Waste Management Services",
    6111: "Elementary and Secondary Schools",
    6112: "Junior Colleges",
    6113: "Colleges, Universities, and Professional Schools",
    6114: "Business Schools and Computer and Management Training",
    6115: "Technical and Trade Schools",
    6116: "Other Schools and Instruction",
    6117: "Educational Support Services",
    6211: "Offices of Physicians",
    6212: "Offices of Dentists",
    6213: "Offices of Other Health Practitioners",
    6214: "Outpatient Care Centers",
    6215: "Medical and Diagnostic Laboratories",
    6216: "Home Health Care Services",
    6219: "Other Ambulatory Health Care Services",
    6221: "General Medical and Surgical Hospitals",
    6222: "Psychiatric and Substance Abuse Hospitals",
    6223: "Specialty (except Psychiatric and Substance Abuse) Hospitals",
    6231: "Nursing Care Facilities (Skilled Nursing Facilities)",
    6232: "Residential Intellectual and Developmental Disability, Mental Health, and Substance Abuse Facilities",
    6233: "Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly",
    6239: "Other Residential Care Facilities",
    6241: "Individual and Family Services",
    6242: "Community Food and Housing, and Emergency and Other Relief Services",
    6243: "Vocational Rehabilitation Services",
    6244: "Child Care Services",
    7111: "Performing Arts Companies",
    7112: "Spectator Sports",
    7113: "Promoters of Performing Arts, Sports, and Similar Events",
    7114: "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures",
    7115: "Independent Artists, Writers, and Performers",
    7121: "Museums, Historical Sites, and Similar Institutions",
    7131: "Amusement Parks and Arcades",
    7132: "Gambling Industries",
    7139: "Other Amusement and Recreation Industries",
    7211: "Traveler Accommodation",
    7212: "RV (Recreational Vehicle) Parks and Recreational Camps",
    7213: "Rooming and Boarding Houses, Dormitories, and Workers' Camps",
    7223: "Special Food Services",
    7224: "Drinking Places (Alcoholic Beverages)",
    7225: "Restaurants and Other Eating Places",
    8111: "Automotive Repair and Maintenance",
    8112: "Electronic and Precision Equipment Repair and Maintenance",
    8113: "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance",
    8114: "Personal and Household Goods Repair and Maintenance",
    8121: "Personal Care Services",
    8122: "Death Care Services",
    8123: "Drycleaning and Laundry Services",
    8129: "Other Personal Services",
    8131: "Religious Organizations",
    8132: "Grantmaking and Giving Services",
    8133: "Social Advocacy Organizations",
    8134: "Civic and Social Organizations",
    8139: "Business, Professional, Labor, Political, and Similar Organizations",
    8141: "Private Households",
    9211: "Executive, Legislative, and Other General Government Support",
    9221: "Justice, Public Order, and Safety Activities",
    9231: "Administration of Human Resource Programs",
    9241: "Administration of Environmental Quality Programs",
    9251: "Administration of Housing Programs, Urban Planning, and Community Development",
    9261: "Administration of Economic Programs",
    9271: "Space Research and Technology",
    9281: "National Security and International Affairs",
}

# NAICS Keywords for 4-digit Subsectors (Complete - All 308 subsectors)
NAICS_KEYWORDS_SUB = {
    1111: ['corn', 'grain', 'oilseed', 'soybean', 'wheat'],
    1112: ['cucumber', 'melon', 'tomato', 'vegetable'],
    1113: ['apple', 'citrus', 'fruit', 'tree nuts'],
    1114: ['flowers', 'greenhouse', 'nursery', 'ornamental'],
    1119: ['cotton', 'hay', 'specialty crops', 'sugarcane'],
    1121: ['beef cattle', 'cattle', 'dairy cow', 'ranch'],
    1122: ['hog', 'pig', 'swine'],
    1123: ['broiler', 'chicken', 'poultry', 'turkey'],
    1124: ['goat', 'lamb', 'sheep', 'wool'],
    1125: ['aquaculture', 'fish farming', 'salmon', 'shellfish'],
    1129: ['animal'],
    1131: ['timber', 'tract', 'operations'],
    1132: ['forest', 'nurseries', 'gathering', 'products'],
    1133: ['logging'],
    1141: ['fishing'],
    1142: ['hunting', 'trapping'],
    1151: ['crop'],
    1152: ['animal'],
    1153: ['forestry'],
    2111: ['fracking', 'gas extraction', 'oil drilling', 'petroleum'],
    2121: ['anthracite', 'coal mining', 'lignite'],
    2122: ['copper mining', 'gold mining', 'iron ore', 'silver'],
    2123: ['gravel', 'limestone', 'sand mining', 'stone quarry'],
    2131: ['mining'],
    2211: ['electric power', 'electricity generation', 'power grid'],
    2212: ['gas utility', 'natural gas distribution'],
    2213: ['sewage treatment', 'wastewater', 'water utility'],
    2361: ['home building', 'house construction', 'residential developer'],
    2362: ['commercial construction', 'office building', 'retail building'],
    2371: ['power line', 'transmission', 'utility infrastructure'],
    2372: ['land development', 'site prep', 'subdivision'],
    2373: ['bridge building', 'highway construction', 'road work'],
    2379: ['heavy', 'civil', 'engineering', 'construction'],
    2381: ['foundation work', 'framing', 'roofing'],
    2382: ['electrical contractor', 'hvac', 'plumbing contractor'],
    2383: ['drywall', 'flooring', 'painting contractor'],
    2389: ['specialty', 'trade', 'contractors'],
    3111: ['animal feed', 'livestock feed', 'pet food'],
    3112: ['flour milling', 'grain mill', 'rice processing'],
    3113: ['candy making', 'chocolate', 'sugar refining'],
    3114: ['canning', 'frozen food', 'fruit processing'],
    3115: ['cheese making', 'dairy processing', 'milk'],
    3116: ['meat packing', 'meat processing', 'slaughterhouse'],
    3117: ['fish packing', 'seafood processing'],
    3118: ['bakery', 'bread making', 'tortilla'],
    3119: ['coffee roasting', 'snack food', 'spice processing'],
    3121: ['beverage', 'food processing', 'manufacturing'],
    3122: ['tobacco', 'manufacturing'],
    3131: ['fiber', 'yarn', 'thread', 'mills', 'manufacturing'],
    3132: ['fabric', 'mills', 'manufacturing'],
    3133: ['textile', 'fabric', 'finishing', 'coating', 'mills', 'clothing', 'fashion'],
    3141: ['textile', 'furnishings', 'mills', 'clothing', 'fashion'],
    3149: ['textile', 'product', 'mills', 'clothing', 'fashion'],
    3151: ['apparel', 'knitting', 'mills', 'textile', 'clothing', 'fashion'],
    3152: ['cut', 'sew', 'apparel', 'textile', 'clothing', 'fashion'],
    3159: ['apparel', 'accessories', 'textile', 'clothing', 'fashion'],
    3161: ['leather', 'hide', 'tanning', 'finishing', 'manufacturing'],
    3162: ['footwear', 'manufacturing'],
    3169: ['leather', 'allied', 'product', 'manufacturing'],
    3211: ['sawmills', 'wood', 'preservation', 'wood products', 'forestry'],
    3212: ['veneer', 'plywood', 'engineered', 'wood', 'product', 'wood products', 'forestry'],
    3219: ['wood', 'product', 'wood products', 'forestry'],
    3221: ['pulp', 'paper', 'paperboard', 'mills', 'wood products', 'forestry'],
    3222: ['converted', 'paper', 'product', 'wood products', 'forestry'],
    3231: ['printing', 'manufacturing'],
    3241: ['petroleum', 'coal', 'products', 'manufacturing'],
    3251: ['basic', 'chemical', 'pharmaceutical'],
    3252: ['resin', 'synthetic', 'rubber', 'artificial', 'fibers', 'manufacturing'],
    3253: ['pesticide', 'fertilizer', 'agricultural', 'chemical', 'pharmaceutical'],
    3254: ['pharmaceutical', 'medicine', 'chemical'],
    3255: ['paint', 'coating', 'adhesive', 'manufacturing'],
    3256: ['soap', 'cleaning', 'compound', 'toilet', 'preparation', 'manufacturing'],
    3259: ['chemical', 'product', 'preparation', 'pharmaceutical'],
    3261: ['plastics', 'product', 'manufacturing'],
    3262: ['rubber', 'product', 'manufacturing'],
    3271: ['clay', 'product', 'refractory', 'manufacturing'],
    3272: ['glass', 'product', 'manufacturing'],
    3273: ['cement', 'concrete', 'product', 'manufacturing'],
    3274: ['lime', 'gypsum', 'product', 'manufacturing'],
    3279: ['nonmetallic', 'mineral', 'product', 'metalworking', 'steel'],
    3311: ['iron', 'steel', 'mills', 'ferroalloy', 'metalworking'],
    3312: ['steel', 'product', 'purchased', 'metalworking'],
    3313: ['alumina', 'aluminum', 'processing', 'metalworking', 'steel'],
    3314: ['nonferrous', 'metal', 'aluminum', 'processing', 'metalworking', 'steel'],
    3315: ['foundries', 'manufacturing'],
    3321: ['forging', 'stamping', 'manufacturing'],
    3322: ['cutlery', 'handtool', 'machinery', 'industrial equipment'],
    3323: ['architectural', 'structural', 'metals', 'metalworking', 'steel'],
    3324: ['boiler', 'tank', 'shipping', 'container', 'manufacturing'],
    3325: ['hardware', 'manufacturing'],
    3326: ['spring', 'wire', 'product', 'manufacturing'],
    3327: ['machine', 'shops', 'turned', 'product', 'screw', 'nut', 'manufacturing'],
    3328: ['coating', 'engraving', 'heat', 'treating', 'allied', 'manufacturing'],
    3329: ['fabricated', 'metal', 'product', 'metalworking', 'steel'],
    3331: ['agriculture', 'construction', 'mining', 'machinery', 'industrial equipment'],
    3332: ['industrial', 'machinery', 'industrial equipment'],
    3333: ['commercial', 'service', 'industry', 'machinery', 'industrial equipment'],
    3334: ['ventilation', 'heating', 'air', 'conditioning', 'commercial', 'refrigeration', 'machinery', 'industrial equipment'],
    3335: ['metalworking', 'machinery', 'steel'],
    3336: ['engine', 'turbine', 'power', 'transmission', 'equipment', 'machinery', 'industrial equipment'],
    3339: ['purpose', 'machinery', 'industrial equipment'],
    3341: ['computer', 'peripheral', 'equipment', 'machinery', 'industrial equipment'],
    3342: ['communications', 'equipment', 'machinery', 'industrial equipment'],
    3343: ['audio', 'video', 'equipment', 'machinery', 'industrial equipment'],
    3344: ['semiconductor', 'electronic', 'component', 'electronics', 'technology'],
    3345: ['navigational', 'measuring', 'electromedical', 'control', 'instruments', 'manufacturing'],
    3346: ['reproducing', 'magnetic', 'optical', 'media', 'manufacturing'],
    3351: ['electric', 'lighting', 'equipment', 'machinery', 'industrial equipment'],
    3352: ['household', 'appliance', 'furniture', 'home goods'],
    3353: ['electrical', 'equipment', 'machinery', 'industrial equipment'],
    3359: ['electrical', 'equipment', 'component', 'machinery', 'industrial equipment'],
    3361: ['motor', 'vehicle', 'automotive', 'transportation'],
    3362: ['motor', 'vehicle', 'body', 'trailer', 'automotive', 'transportation'],
    3363: ['motor', 'vehicle', 'parts', 'automotive', 'transportation'],
    3364: ['aerospace', 'product', 'parts', 'manufacturing'],
    3365: ['railroad', 'rolling', 'stock', 'manufacturing'],
    3366: ['ship', 'boat', 'building', 'manufacturing'],
    3369: ['transportation', 'equipment', 'machinery', 'industrial equipment'],
    3371: ['household', 'institutional', 'furniture', 'kitchen', 'cabinet', 'home goods'],
    3372: ['office', 'furniture', 'fixtures', 'home goods'],
    3379: ['furniture', 'product', 'home goods'],
    3391: ['medical', 'equipment', 'supplies', 'machinery', 'industrial equipment'],
    3399: ['miscellaneous', 'manufacturing'],
    4231: ['motor', 'vehicle', 'parts', 'supplies', 'wholesale', 'distribution', 'b2b', 'automotive'],
    4232: ['furniture', 'home', 'furnishing', 'wholesale', 'distribution', 'b2b'],
    4233: ['lumber', 'construction', 'materials', 'wholesale', 'distribution', 'b2b'],
    4234: ['professional', 'commercial', 'equipment', 'supplies', 'wholesale', 'distribution', 'b2b'],
    4235: ['metal', 'mineral', 'petroleum', 'wholesale', 'distribution', 'b2b'],
    4236: ['household', 'appliances', 'electrical', 'electronic', 'goods', 'wholesale', 'distribution', 'b2b'],
    4237: ['hardware', 'plumbing', 'heating', 'equipment', 'supplies', 'wholesale', 'distribution', 'b2b'],
    4238: ['machinery', 'equipment', 'supplies', 'wholesale', 'distribution', 'b2b'],
    4239: ['miscellaneous', 'durable', 'goods', 'wholesale', 'distribution', 'b2b'],
    4241: ['paper', 'product', 'wholesale', 'distribution', 'b2b'],
    4242: ['drugs', 'druggists', 'sundries', 'wholesale', 'distribution', 'b2b', 'pharmaceutical', 'medical supplies'],
    4243: ['apparel', 'piece', 'goods', 'notions', 'wholesale', 'distribution', 'b2b'],
    4244: ['grocery', 'product', 'wholesale', 'distribution', 'b2b', 'food distribution'],
    4245: ['farm', 'product', 'raw', 'material', 'wholesale', 'distribution', 'b2b'],
    4246: ['chemical', 'allied', 'products', 'wholesale', 'distribution', 'b2b'],
    4247: ['petroleum', 'products', 'wholesale', 'distribution', 'b2b'],
    4248: ['beer', 'wine', 'distilled', 'alcoholic', 'beverage', 'wholesale', 'distribution', 'b2b'],
    4249: ['miscellaneous', 'nondurable', 'goods', 'wholesale', 'distribution', 'b2b'],
    4251: ['wholesale', 'trade', 'agents', 'brokers', 'distribution', 'b2b'],
    4411: ['automobile', 'retail', 'store', 'shopping', 'car dealer', 'automotive'],
    4412: ['motor', 'vehicle', 'automotive', 'retail', 'store', 'shopping', 'car dealer'],
    4413: ['automotive', 'parts', 'accessories', 'tire', 'retail', 'store', 'shopping'],
    4441: ['building', 'material', 'supplies', 'retail', 'store', 'shopping'],
    4442: ['lawn', 'garden', 'equipment', 'supplies', 'retail', 'store', 'shopping'],
    4451: ['grocery', 'convenience', 'retail', 'store', 'shopping', 'food'],
    4452: ['specialty', 'food', 'retail', 'store', 'shopping', 'grocery'],
    4453: ['beer', 'wine', 'liquor', 'retail', 'store', 'shopping'],
    4491: ['furniture', 'home', 'furnishings', 'retail', 'store', 'shopping'],
    4492: ['electronics', 'appliance', 'retail', 'store', 'shopping', 'technology'],
    4551: ['department', 'retail', 'store', 'shopping'],
    4552: ['warehouse', 'clubs', 'supercenters', 'merchandise', 'retail', 'store', 'shopping'],
    4561: ['health', 'personal', 'care', 'healthcare', 'retail', 'store', 'shopping', 'pharmacy'],
    4571: ['gasoline', 'stations', 'retail', 'store', 'shopping'],
    4572: ['fuel', 'retail', 'store', 'shopping'],
    4581: ['clothing', 'accessories', 'retail', 'store', 'shopping', 'fashion'],
    4582: ['shoe', 'retail', 'store', 'shopping'],
    4583: ['jewelry', 'luggage', 'leather', 'goods', 'retail', 'store', 'shopping'],
    4591: ['sporting', 'goods', 'hobby', 'musical', 'instrument', 'retail', 'store', 'shopping'],
    4592: ['book', 'news', 'retail', 'store', 'shopping'],
    4593: ['florists', 'retail', 'store', 'shopping'],
    4594: ['office', 'supplies', 'stationery', 'gift', 'retail', 'store', 'shopping'],
    4595: ['used', 'merchandise', 'retail', 'store', 'shopping'],
    4599: ['miscellaneous', 'retail', 'store', 'shopping'],
    4811: ['scheduled', 'air', 'transportation', 'logistics', 'aviation', 'airline'],
    4812: ['nonscheduled', 'air', 'transportation', 'logistics', 'aviation', 'airline'],
    4821: ['rail', 'transportation', 'logistics', 'railroad'],
    4831: ['deep', 'sea', 'coastal', 'great', 'lakes', 'water', 'transportation', 'logistics'],
    4832: ['inland', 'water', 'transportation', 'logistics', 'maritime', 'shipping'],
    4841: ['freight', 'trucking', 'transportation', 'logistics'],
    4842: ['specialized', 'freight', 'trucking', 'transportation', 'logistics'],
    4851: ['urban', 'transit', 'systems', 'transportation', 'logistics'],
    4852: ['interurban', 'rural', 'bus', 'transportation', 'logistics'],
    4853: ['taxi', 'limousine', 'service', 'transportation', 'logistics'],
    4854: ['school', 'employee', 'bus', 'transportation', 'logistics'],
    4855: ['charter', 'bus', 'industry', 'transportation', 'logistics'],
    4859: ['transit', 'ground', 'passenger', 'transportation', 'logistics'],
    4861: ['pipeline', 'transportation', 'crude', 'oil', 'logistics', 'energy'],
    4862: ['pipeline', 'transportation', 'natural', 'gas', 'logistics', 'energy'],
    4869: ['pipeline', 'transportation', 'logistics', 'energy'],
    4871: ['scenic', 'sightseeing', 'transportation', 'land', 'logistics'],
    4872: ['scenic', 'sightseeing', 'transportation', 'water', 'logistics', 'maritime', 'shipping'],
    4879: ['scenic', 'sightseeing', 'transportation', 'logistics'],
    4881: ['air', 'transportation', 'logistics', 'aviation', 'airline'],
    4882: ['rail', 'transportation', 'logistics', 'railroad'],
    4883: ['water', 'transportation', 'logistics', 'maritime', 'shipping'],
    4884: ['road', 'transportation', 'logistics'],
    4885: ['freight', 'transportation', 'arrangement', 'logistics', 'trucking'],
    4889: ['transportation', 'logistics'],
    4911: ['postal', 'service', 'transportation', 'logistics'],
    4921: ['couriers', 'express', 'delivery', 'transportation', 'logistics'],
    4922: ['local', 'messengers', 'delivery', 'transportation', 'logistics'],
    4931: ['warehousing', 'storage', 'transportation', 'logistics'],
    5121: ['film studio', 'motion', 'movie production', 'picture', 'video', 'video production'],
    5122: ['music production', 'record label', 'sound', 'sound recording'],
    5131: ['book', 'book publishing', 'directory', 'magazine', 'newspaper', 'periodical', 'publishers'],
    5132: ['api', 'app', 'application', 'code', 'computer', 'data', 'database', 'developer', 'development', 'digital', 'game developer', 'git', 'github', 'internet', 'online', 'platform', 'programming', 'server', 'software', 'software publisher', 'system', 'tech', 'technology', 'website'],
    5161: ['broadcasting', 'radio', 'radio station', 'stations', 'television', 'tv station'],
    5162: ['content platform', 'facebook', 'instagram', 'linkedin', 'media', 'networks', 'social', 'social media', 'streaming', 'streaming service', 'twitter'],
    5171: ['satellite', 'telecom', 'telecommunications', 'wired', 'wireless'],
    5174: ['satellite', 'telecommunications'],
    5178: ['telecommunications'],
    5182: ['api', 'app', 'application', 'aws', 'azure', 'cloud', 'cloud computing', 'code', 'computer', 'computing', 'data', 'data center', 'database', 'developer', 'development', 'digital', 'git', 'github', 'google', 'hosting', 'iaas', 'infrastructure', 'internet', 'microsoft', 'online', 'paas', 'platform', 'programming', 'saas', 'server', 'system', 'tech', 'technology', 'web hosting', 'website'],
    5192: ['api', 'app', 'application', 'archives', 'computer', 'data', 'database', 'digital', 'information', 'internet', 'libraries', 'online', 'platform', 'search', 'server', 'system', 'tech', 'technology', 'web search', 'website'],
    5211: ['authorities-central', 'central bank', 'currency management', 'federal reserve', 'international reserves', 'monetary', 'monetary policy'],
    5221: ['accepting deposits', 'bank', 'banking', 'budget', 'cashflow', 'checking', 'commercial bank', 'commercial banking', 'credit union', 'credit unions', 'debit', 'depository', 'expense', 'finance', 'financial', 'fintech', 'money', 'pay', 'payment', 'payroll', 'revenue', 'savings account', 'savings bank', 'savings institutions', 'treasury', 'wallet'],
    5222: ['apr', 'auto loan', 'budget', 'cashflow', 'compound interest', 'consumer lending', 'credit', 'debit', 'expense', 'finance', 'finance company', 'financial', 'fintech', 'interest rate', 'loan', 'money', 'mortgage', 'mortgage company', 'nondepository', 'pawnbrokers', 'pay', 'payment', 'payroll', 'personal loan', 'real estate credit', 'refinance', 'revenue', 'sales financing', 'treasury', 'wallet'],
    5223: ['billing', 'cashapp', 'check cashing', 'collections', 'credit reporting', 'debt collection', 'intermediation', 'invoice', 'ledger', 'loan servicing', 'money transfer', 'paypal', 'peer-to-peer payments', 'plaid', 'quickbooks', 'sage', 'square', 'stripe', 'venmo', 'xero'],
    5231: ['annuity', 'binance', 'blockchain', 'bond', 'brokerage', 'brokerages', 'coinbase', 'commodity brokerage', 'crypto', 'cryptocurrency', 'debit', 'dividend', 'equity', 'fintech', 'invest', 'investment', 'investment banking', 'ira', 'money', 'pay', 'payment', 'portfolio management', 'robinhood', 'securities brokerage', 'securities trading', 'stock', 'stock brokerage', 'stock trading', 'trade', 'trading', 'wallet'],
    5232: ['annuity', 'bond', 'commodity', 'commodity exchange', 'commodity trading', 'crypto exchange', 'debit', 'dividend', 'electronic marketplace', 'equity', 'exchange', 'exchanges', 'fintech', 'forex', 'futures', 'ira', 'money', 'nasdaq', 'nyse', 'pay', 'payment', 'portfolio management', 'stock exchange', 'wallet'],
    5239: ['annuity', 'asset management', 'billing', 'bond', 'budget', 'cashflow', 'crypto clearinghouse', 'custody services', 'dividend', 'equity', 'etf', 'expense', 'fiduciary services', 'finance', 'financial', 'funds', 'hedge funds', 'investment advice', 'invoice', 'ira', 'ledger', 'mutual fund', 'mutual funds', 'payroll', 'portfolio', 'portfolio management', 'revenue', 'robo-advisor', 'treasury', 'trust services', 'venture capital', 'wealth management'],
    5241: ['actuarial', 'auto insurance', 'carriers', 'casualty', 'direct insurance', 'health insurance', 'insurance', 'life insurance', 'property insurance', 'reinsurance', 'underwriting'],
    5242: ['agencies', 'agent', 'claims adjustment', 'insurance agency', 'insurance broker', 'third-party administration'],
    5251: ['401k', 'annuity', 'benefit', 'billing', 'bond', 'budget', 'cashflow', 'dividend', 'employee benefit', 'employee benefits', 'equity', 'expense', 'finance', 'financial', 'health and welfare funds', 'invoice', 'ira', 'ledger', 'payroll', 'pension', 'pension fund', 'portfolio management', 'retirement', 'revenue', 'self-insurance funds', 'treasury'],
    5259: ['REITs', 'estates', 'investment fund', 'investment pool', 'mutual funds', 'pools', 'private equity', 'trusts', 'venture capital'],
    5311: ['property rental', 'real estate lessor'],
    5312: ['property broker', 'real estate agent', 'realtor'],
    5313: ['property management', 'real estate services'],
    5321: ['car rental', 'equipment leasing', 'truck rental'],
    5322: ['equipment rental', 'party rental', 'tool rental'],
    5323: ['rental', 'centers'],
    5324: ['commercial', 'industrial', 'machinery', 'equipment', 'rental', 'leasing'],
    5331: ['lessors', 'nonfinancial', 'intangible', 'assets', 'copyrighted', 'works'],
    5411: ['attorney', 'law firm', 'lawyer', 'legal', 'legal services'],
    5412: ['accounting', 'accounting firm', 'bookkeeping', 'cpa', 'payroll', 'tax', 'tax preparation'],
    5413: ['architectural', 'architecture', 'engineering', 'engineering firm', 'surveying'],
    5414: ['graphic design', 'interior design', 'specialized design'],
    5415: ['computer', 'programming', 'software', 'software development', 'system design'],
    5416: ['business consulting', 'consulting', 'management consulting'],
    5417: ['r&d', 'research lab', 'scientific', 'scientific research'],
    5418: ['advertising', 'advertising agency', 'marketing', 'pr firm', 'public'],
    5419: ['photography', 'professional', 'translation', 'veterinary'],
    5511: ['management'],
    5611: ['office', 'administrative'],
    5612: ['facilities'],
    5613: ['employment'],
    5614: ['business'],
    5615: ['travel', 'arrangement', 'reservation'],
    5616: ['investigation', 'security'],
    5617: ['buildings', 'dwellings'],
    5619: ['support services'],
    5621: ['waste', 'collection'],
    5622: ['waste', 'treatment', 'disposal'],
    5629: ['remediation', 'waste', 'management'],
    6111: ['elementary', 'secondary', 'schools'],
    6112: ['junior', 'colleges'],
    6113: ['colleges', 'universities', 'professional', 'schools'],
    6114: ['business', 'schools', 'computer', 'management', 'training'],
    6115: ['technical', 'trade', 'schools'],
    6116: ['schools', 'instruction'],
    6117: ['educational'],
    6211: ['doctor office', 'physician practice'],
    6212: ['dental office', 'dentist'],
    6213: ['chiropractor', 'optometrist', 'therapist'],
    6214: ['outpatient clinic', 'surgery center'],
    6215: ['diagnostic lab', 'medical lab'],
    6216: ['home healthcare', 'nursing services'],
    6219: ['ambulatory', 'health', 'care', 'healthcare'],
    6221: ['hospital', 'medical center'],
    6222: ['mental health', 'psychiatric hospital'],
    6223: ['specialty', 'psychiatric', 'substance', 'abuse', 'hospitals'],
    6231: ['nursing home', 'skilled nursing'],
    6232: ['residential', 'intellectual', 'developmental', 'disability', 'mental', 'health'],
    6233: ['assisted living', 'senior care'],
    6239: ['residential', 'care', 'facilities'],
    6241: ['individual', 'family'],
    6242: ['community', 'food', 'housing', 'emergency', 'relief', 'food service'],
    6243: ['vocational', 'rehabilitation'],
    6244: ['child', 'care'],
    7111: ['performing', 'arts'],
    7112: ['spectator', 'sports'],
    7113: ['promoters', 'performing', 'arts', 'sports', 'events'],
    7114: ['agents', 'managers', 'artists', 'athletes', 'entertainers', 'public'],
    7115: ['independent', 'artists', 'writers', 'performers'],
    7121: ['museums', 'historical', 'sites', 'institutions'],
    7131: ['amusement', 'parks', 'arcades'],
    7132: ['gambling'],
    7139: ['amusement', 'recreation'],
    7211: ['traveler', 'accommodation'],
    7212: ['recreational', 'vehicle', 'parks', 'camps'],
    7213: ['rooming', 'boarding', 'houses', 'dormitories', 'workers', 'camps'],
    7223: ['food', 'food service'],
    7224: ['drinking', 'places', 'alcoholic', 'beverages'],
    7225: ['restaurants', 'eating', 'places'],
    8111: ['automotive', 'repair', 'maintenance'],
    8112: ['electronic', 'precision', 'equipment', 'repair', 'maintenance'],
    8113: ['commercial', 'industrial', 'machinery', 'equipment', 'automotive', 'electronic'],
    8114: ['personal', 'household', 'goods', 'repair', 'maintenance'],
    8121: ['personal', 'care'],
    8122: ['death', 'care'],
    8123: ['drycleaning', 'laundry'],
    8129: ['personal'],
    8131: ['religious', 'organizations'],
    8132: ['grantmaking', 'giving'],
    8133: ['social', 'advocacy', 'organizations'],
    8134: ['civic', 'social', 'organizations'],
    8139: ['business', 'professional', 'labor', 'political', 'organizations'],
    8141: ['private', 'households'],
    9211: ['executive', 'legislative', 'government'],
    9221: ['justice', 'public', 'order', 'safety'],
    9231: ['administration', 'human', 'resource', 'programs'],
    9241: ['administration', 'environmental', 'quality', 'programs'],
    9251: ['administration', 'housing', 'programs', 'urban', 'planning', 'community'],
    9261: ['administration', 'economic', 'programs'],
    9271: ['space', 'research', 'technology'],
    9281: ['national', 'security', 'international', 'affairs'],
}

# Keyword mappings for each NAICS sector (aggregated from all subsectors)
NAICS_KEYWORDS = {
    # Agriculture, Forestry, Fishing and Hunting (11)
    11: [
        'agricultural', 'agriculture', 'agtech', 'animal', 'apple', 
        'aquaculture', 'beef cattle', 'broiler', 'cattle', 'chicken', 'citrus', 
        'corn', 'cotton', 'crop', 'cucumber', 'dairy cow', 'egg', 'farm', 
        'farming', 'fish farming', 'fishing', 'floriculture', 'flowers', 
        'food production', 'forest', 'forestry', 'fruit', 'gathering', 'goat', 
        'grain', 'greenhouse', 'hay', 'hog', 'hunting', 'irrigation', 'lamb', 
        'livestock', 'logging', 'melon', 'nurseries', 'nursery', 'oilseed', 
        'operations', 'organic', 'ornamental', 'pig', 'poultry', 
        'precision agriculture', 'production', 'products', 'ranch', 'ranching', 
        'salmon', 'sheep', 'shellfish', 'soybean', 'specialty crops', 
        'sugarcane', 'sustainable', 'swine', 'timber', 'tomato', 'tract', 
        'trapping', 'tree', 'tree nuts', 'turkey', 'vegetable', 'wheat', 'wool'
    ],

    # Mining, Quarrying, and Oil and Gas Extraction (21)
    21: [
        'anthracite', 'coal', 'coal mining', 'copper mining', 'drilling', 
        'energy extraction', 'extraction', 'fracking', 'gas', 'gas extraction', 
        'gold mining', 'gravel', 'iron ore', 'lignite', 'limestone', 'metal', 
        'mineral', 'mining', 'natural gas', 'nonmetallic', 'oil', 
        'oil drilling', 'ore', 'petroleum', 'quarry', 'quarrying', 'refinery', 
        'sand mining', 'silver', 'stone quarry'
    ],

    # Utilities (22)
    22: [
        'distribution', 'electric', 'electric power', 'electricity', 
        'electricity generation', 'energy', 'gas', 'gas utility', 'grid', 
        'infrastructure', 'meter', 'natural', 'natural gas distribution', 
        'power', 'power grid', 'renewable', 'sewage', 'sewage treatment', 
        'smart grid', 'solar', 'transmission', 'utilities', 'utility', 
        'wastewater', 'water', 'water utility', 'wind'
    ],

    # Construction (23)
    23: [
        'architecture', 'bridge', 'bridge building', 'builder', 'building', 
        'civil', 'commercial construction', 'construction', 'contractor', 
        'contractors', 'drywall', 'electrical contractor', 'engineering', 
        'exterior', 'finishing', 'flooring', 'foundation work', 'framing', 
        'heavy', 'highway', 'highway construction', 'home building', 
        'house construction', 'hvac', 'infrastructure', 'land', 
        'land development', 'maintenance', 'nonresidential', 'office building', 
        'painting contractor', 'plumbing contractor', 'power line', 
        'project management', 'renovation', 'repair', 'residential', 
        'residential developer', 'retail building', 'road work', 'roofing', 
        'site prep', 'specialty', 'street', 'subdivision', 'trade', 
        'transmission', 'utility', 'utility infrastructure'
    ],

    # Manufacturing (31)
    31: [
        'accessories', 'adhesive', 'aerospace', 'agricultural', 'agriculture', 
        'air', 'allied', 'alumina', 'aluminum', 'animal feed', 'apparel', 
        'appliance', 'architectural', 'artificial', 'assembly', 'audio', 
        'automation', 'automotive', 'bakery', 'basic', 'beverage', 'boat', 
        'body', 'boiler', 'bread making', 'building', 'cabinet', 
        'candy making', 'canning', 'cement', 'cheese making', 'chemical', 
        'chocolate', 'clay', 'cleaning', 'clothing', 'coal', 'coating', 
        'coffee roasting', 'commercial', 'communications', 'component', 
        'compound', 'computer', 'concrete', 'conditioning', 'construction', 
        'container', 'control', 'converted', 'cut', 'cutlery', 
        'dairy processing', 'electric', 'electrical', 'electromedical', 
        'electronic', 'electronics', 'engine', 'engineered', 'engraving', 
        'equipment', 'erp', 'fabric', 'fabricated', 'factory', 'fashion', 
        'ferroalloy', 'fertilizer', 'fiber', 'fibers', 'finishing', 
        'fish packing', 'fixtures', 'flour milling', 'food processing', 
        'footwear', 'forestry', 'forging', 'foundries', 'frozen food', 
        'fruit processing', 'furnishings', 'furniture', 'glass', 'grain mill', 
        'gypsum', 'handtool', 'hardware', 'heat', 'heating', 'hide', 
        'home goods', 'household', 'industrial', 'industrial equipment', 
        'industry', 'institutional', 'instruments', 'inventory', 'iron', 
        'kitchen', 'knitting', 'lean', 'leather', 'lighting', 'lime', 
        'livestock feed', 'machine', 'machinery', 'magnetic', 'manufacturing', 
        'measuring', 'meat packing', 'meat processing', 'media', 'medical', 
        'medicine', 'metal', 'metals', 'metalworking', 'milk', 'mills', 
        'mineral', 'mining', 'miscellaneous', 'motor', 'mrp', 'navigational', 
        'nonferrous', 'nonmetallic', 'nut', 'office', 'optical', 'paint', 
        'paper', 'paperboard', 'parts', 'peripheral', 'pesticide', 'pet food', 
        'petroleum', 'pharmaceutical', 'plastics', 'plywood', 'power', 
        'preparation', 'preservation', 'printing', 'processing', 'product', 
        'production', 'production planning', 'products', 'pulp', 'purchased', 
        'purpose', 'quality control', 'railroad', 'refractory', 
        'refrigeration', 'reproducing', 'resin', 'rice processing', 'rolling', 
        'rubber', 'sawmills', 'screw', 'seafood processing', 'semiconductor', 
        'service', 'sew', 'ship', 'shipping', 'shops', 'six sigma', 
        'slaughterhouse', 'snack food', 'soap', 'spice processing', 'spring', 
        'stamping', 'steel', 'stock', 'structural', 'sugar refining', 
        'supplies', 'supply chain', 'synthetic', 'tank', 'tanning', 
        'technology', 'textile', 'thread', 'tobacco', 'toilet', 'tortilla', 
        'trailer', 'transmission', 'transportation', 'treating', 'turbine', 
        'turned', 'vehicle', 'veneer', 'ventilation', 'video', 'wire', 'wood', 
        'wood products', 'yarn'
    ],

    # Wholesale Trade (42)
    42: [
        'agents', 'alcoholic', 'allied', 'apparel', 'appliances', 'automotive', 
        'b2b', 'beer', 'beverage', 'brokers', 'bulk', 'business to business', 
        'chemical', 'commercial', 'construction', 'distilled', 'distribution', 
        'distributor', 'druggists', 'drugs', 'durable', 'electrical', 
        'electronic', 'equipment', 'export', 'farm', 'food distribution', 
        'furnishing', 'furniture', 'goods', 'grocery', 'hardware', 'heating', 
        'home', 'household', 'import', 'lumber', 'machinery', 'material', 
        'materials', 'medical supplies', 'metal', 'mineral', 'miscellaneous', 
        'motor', 'nondurable', 'notions', 'paper', 'parts', 'petroleum', 
        'pharmaceutical', 'piece', 'plumbing', 'procurement', 'product', 
        'products', 'professional', 'raw', 'sundries', 'supplier', 'supplies', 
        'trade', 'vehicle', 'wholesale', 'wine'
    ],

    # Retail Trade (44)
    44: [
        'accessories', 'amazon', 'appliance', 'automobile', 'automotive', 
        'beer', 'book', 'building', 'buy', 'car dealer', 'care', 'cart', 
        'catalog', 'checkout', 'clothing', 'clubs', 'convenience', 'customer', 
        'department', 'e-commerce', 'ebay', 'ecommerce', 'electronics', 
        'equipment', 'fashion', 'florists', 'food', 'fuel', 'fulfillment', 
        'furnishings', 'furniture', 'garden', 'gasoline', 'gift', 'goods', 
        'grocery', 'health', 'healthcare', 'hobby', 'home', 'instrument', 
        'inventory', 'jewelry', 'lawn', 'leather', 'liquor', 'luggage', 
        'magento', 'marketplace', 'material', 'merchandise', 'merchant', 
        'miscellaneous', 'motor', 'musical', 'news', 'office', 'order', 
        'parts', 'personal', 'pharmacy', 'point of sale', 'pos', 'product', 
        'purchase', 'retail', 'sales', 'selling', 'shoe', 'shop', 'shopify', 
        'shopping', 'specialty', 'sporting', 'stationery', 'stations', 'store', 
        'supercenters', 'supplies', 'technology', 'tire', 'used', 'vehicle', 
        'warehouse', 'wine', 'woocommerce'
    ],

    # Transportation and Warehousing (48)
    48: [
        'air', 'airline', 'arrangement', 'auto', 'aviation', 'bus', 'car', 
        'cargo', 'charter', 'coastal', 'couriers', 'crude', 'deep', 'delivery', 
        'dispatch', 'distribution', 'employee', 'energy', 'express', 'fedex', 
        'fleet', 'freight', 'gas', 'gps', 'great', 'ground', 'industry', 
        'inland', 'interurban', 'lakes', 'land', 'limousine', 'local', 
        'logistics', 'lyft', 'maps', 'maritime', 'messengers', 'natural', 
        'navigation', 'nonscheduled', 'oil', 'passenger', 'pipeline', 'postal', 
        'rail', 'railroad', 'ride', 'road', 'route', 'rural', 'scenic', 
        'scheduled', 'school', 'sea', 'service', 'shipping', 'sightseeing', 
        'specialized', 'storage', 'supply chain', 'systems', 'taxi', 
        'tracking', 'transit', 'transport', 'transportation', 'travel', 'trip', 
        'truck', 'trucking', 'uber', 'ups', 'urban', 'vehicle', 'warehouse', 
        'warehousing', 'water'
    ],

    # Information (51)
    51: [
        'ai', 'analytics', 'api', 'app', 'application', 'archives', 
        'artificial intelligence', 'automation', 'aws', 'azure', 'blog', 
        'book', 'book publishing', 'bot', 'broadcasting', 'chatbot', 'cloud', 
        'cloud computing', 'cms', 'code', 'collaboration', 'communication', 
        'computer', 'computing', 'content', 'content platform', 'data', 
        'data center', 'database', 'developer', 'development', 'devops', 
        'digital', 'directory', 'distribution', 'facebook', 'film studio', 
        'game developer', 'git', 'github', 'google', 'hosting', 'iaas', 
        'information', 'infrastructure', 'instagram', 'integration', 
        'internet', 'libraries', 'linkedin', 'machine learning', 'magazine', 
        'media', 'messaging', 'microsoft', 'ml', 'motion', 'movie production', 
        'music production', 'networks', 'news', 'newspaper', 'notification', 
        'online', 'paas', 'periodical', 'picture', 'platform', 'processing', 
        'productivity', 'programming', 'providers', 'publishers', 'radio', 
        'radio station', 'record label', 'recording', 'saas', 'satellite', 
        'search', 'server', 'social', 'social media', 'software', 
        'software publisher', 'sound', 'sound recording', 'stations', 
        'streaming', 'streaming service', 'system', 'tech', 'technology', 
        'telecom', 'telecommunications', 'television', 'tv station', 'twitter', 
        'video', 'video production', 'web', 'web hosting', 'web search', 
        'website', 'wired', 'wireless', 'workflow'
    ],

    # Finance and Insurance (52)
    52: ['401k', 'REITs', 'accepting deposits', 'actuarial', 'agencies', 'agent', 'annuity', 'apr', 'asset management', 'authorities-central', 'auto insurance', 'auto loan', 'bank', 'banking', 'benefit', 'billing', 'binance', 'blockchain', 'bond', 'brokerage', 'brokerages', 'budget', 'carriers', 'cashapp', 'cashflow', 'casualty', 'central bank', 'check cashing', 'checking', 'claims adjustment', 'coinbase', 'collections', 'commercial bank', 'commercial banking', 'commodity', 'commodity brokerage', 'commodity exchange', 'commodity trading', 'compound interest', 'consumer lending', 'credit', 'credit reporting', 'credit union', 'credit unions', 'crypto', 'crypto clearinghouse', 'crypto exchange', 'cryptocurrency', 'currency management', 'custody services', 'debit', 'debt collection', 'depository', 'direct insurance', 'dividend', 'electronic marketplace', 'employee benefit', 'employee benefits', 'equity', 'estates', 'etf', 'exchange', 'exchanges', 'expense', 'federal reserve', 'fiduciary services', 'finance', 'finance company', 'financial', 'fintech', 'forex', 'funds', 'futures', 'health and welfare funds', 'health insurance', 'hedge funds', 'insurance', 'insurance agency', 'insurance broker', 'interest rate', 'intermediation', 'international reserves', 'invest', 'investment', 'investment advice', 'investment banking', 'investment fund', 'investment pool', 'invoice', 'ira', 'ledger', 'life insurance', 'loan', 'loan servicing', 'monetary', 'monetary policy', 'money', 'money transfer', 'mortgage', 'mortgage company', 'mutual fund', 'mutual funds', 'nasdaq', 'nondepository', 'nyse', 'pawnbrokers', 'pay', 'payment', 'paypal', 'payroll', 'peer-to-peer payments', 'pension', 'pension fund', 'personal loan', 'plaid', 'pools', 'portfolio', 'portfolio management', 'private equity', 'property insurance', 'quickbooks', 'real estate credit', 'refinance', 'reinsurance', 'retirement', 'revenue', 'robinhood', 'robo-advisor', 'sage', 'sales financing', 'savings account', 'savings bank', 'savings institutions', 'securities brokerage', 'securities trading', 'self-insurance funds', 'square', 'stock', 'stock brokerage', 'stock exchange', 'stock trading', 'stripe', 'third-party administration', 'trade', 'trading', 'treasury', 'trust services', 'trusts', 'underwriting', 'venmo', 'venture capital', 'wallet', 'wealth management', 'xero'],

    # Real Estate and Rental and Leasing (53)
    53: [
        'airbnb', 'apartment', 'assets', 'automotive', 'booking', 'broker', 
        'brokers', 'car rental', 'centers', 'commercial', 'condo', 'consumer', 
        'copyrighted', 'equipment', 'equipment leasing', 'equipment rental', 
        'estate', 'goods', 'home', 'house', 'housing', 'industrial', 
        'intangible', 'lease', 'leasing', 'lessors', 'listing', 'machinery', 
        'mls', 'mortgage', 'nonfinancial', 'party rental', 'property', 
        'property broker', 'property management', 'property rental', 
        'real estate', 'real estate agent', 'real estate lessor', 
        'real estate services', 'realtor', 'redfin', 'rent', 'rental', 
        'tool rental', 'truck rental', 'vrbo', 'works', 'zillow'
    ],

    # Professional, Scientific, and Technical Services (54)
    54: [
        'accounting', 'accounting firm', 'advertising', 'advertising agency', 
        'analysis', 'analytics', 'architect', 'architectural', 'architecture', 
        'attorney', 'audit', 'bookkeeping', 'business consulting', 
        'business intelligence', 'computer', 'consultant', 'consulting', 'cpa', 
        'creative', 'data analysis', 'design', 'engineering', 
        'engineering firm', 'graphic design', 'interior design', 'law', 
        'law firm', 'lawyer', 'legal', 'legal services', 
        'management consulting', 'marketing', 'optimization', 'payroll', 
        'photography', 'pr firm', 'preparation', 'professional', 'programming', 
        'public', 'r&d', 'research', 'research lab', 'science', 'scientific', 
        'scientific research', 'seo', 'software', 'software development', 
        'specialized design', 'strategy', 'surveying', 'system design', 'tax', 
        'tax preparation', 'translation', 'veterinary'
    ],

    # Management of Companies and Enterprises (55)
    55: [
        'companies', 'conglomerate', 'corporate', 'enterprise', 'enterprises', 
        'headquarters', 'holding company', 'management', 'parent company', 
        'portfolio management', 'subsidiary'
    ],

    # Administrative and Support and Waste Management and Remediation Services (56)
    56: [
        'administrative', 'arrangement', 'buildings', 'business', 'cleaning', 
        'collection', 'disposal', 'dwellings', 'employment', 'facilities', 
        'facility', 'hr', 'human resources', 'investigation', 'management', 
        'office', 'office management', 'payroll', 'recruiting', 'remediation', 
        'reservation', 'security', 'staffing', 'support', 'temp', 'travel', 
        'treatment', 'virtual assistant', 'waste'
    ],

    # Educational Services (61)
    61: [
        'academic', 'business', 'certification', 'classroom', 'college', 
        'colleges', 'computer', 'course', 'curriculum', 'education', 
        'educational', 'elearning', 'elementary', 'exam', 'grade', 
        'instruction', 'junior', 'learning', 'learning management', 'lesson', 
        'lms', 'management', 'mooc', 'online learning', 'professional', 
        'research', 'school', 'schools', 'secondary', 'student', 'study', 
        'teacher', 'technical', 'trade', 'training', 'tutorial', 
        'universities', 'university'
    ],

    # Health Care and Social Assistance (62)
    62: [
        'abuse', 'ambulatory', 'assisted', 'assisted living', 'care', 
        'centers', 'child', 'chiropractor', 'clinic', 'communities', 
        'community', 'continuing', 'dental', 'dental office', 'dentist', 
        'dentists', 'developmental', 'diagnostic', 'diagnostic lab', 
        'disability', 'doctor', 'doctor office', 'drug', 'ehr', 'emergency', 
        'emr', 'facilities', 'family', 'fitness', 'food', 'food service', 
        'health', 'healthcare', 'hipaa', 'home', 'home healthcare', 'hospital', 
        'hospitals', 'housing', 'individual', 'insurance', 'intellectual', 
        'laboratories', 'living', 'medicaid', 'medical', 'medical center', 
        'medical lab', 'medical records', 'medicare', 'medicine', 'mental', 
        'mental health', 'nursing', 'nursing home', 'nursing services', 
        'optometrist', 'outpatient', 'outpatient clinic', 'patient', 
        'pharmaceutical', 'physician practice', 'physicians', 'practitioners', 
        'psychiatric', 'psychiatric hospital', 'rehabilitation', 'relief', 
        'residential', 'retirement', 'senior care', 'skilled', 
        'skilled nursing', 'specialty', 'substance', 'surgery center', 
        'surgical', 'telehealth', 'telemedicine', 'therapist', 'therapy', 
        'treatment', 'vision', 'vocational', 'wellness'
    ],

    # Arts, Entertainment, and Recreation (71)
    71: [
        'agents', 'amusement', 'animation', 'arcades', 'art', 'artists', 
        'arts', 'athletes', 'companies', 'creative', 'design', 'entertainers', 
        'entertainment', 'events', 'figures', 'film', 'fitness', 'gambling', 
        'game', 'gaming', 'gym', 'historical', 'independent', 'instagram', 
        'institutions', 'managers', 'media', 'movie', 'museums', 'music', 
        'netflix', 'parks', 'performers', 'performing', 'photography', 
        'podcast', 'promoters', 'public', 'recreation', 'sites', 
        'social media', 'spectator', 'sport', 'sports', 'spotify', 'streaming', 
        'tiktok', 'twitch', 'video', 'writers', 'youtube'
    ],

    # Accommodation and Food Services (72)
    72: [
        'accommodation', 'alcoholic', 'bar', 'beverages', 'boarding', 
        'booking', 'cafe', 'camps', 'catering', 'cooking', 'delivery', 
        'dining', 'doordash', 'dormitories', 'drinking', 'eating', 'food', 
        'food service', 'grubhub', 'guest services', 'hospitality', 'hotel', 
        'houses', 'kitchen', 'menu', 'motel', 'parks', 'places', 'pos', 
        'recipe', 'recreational', 'reservation', 'restaurant', 'restaurants', 
        'rooming', 'special', 'table management', 'takeout', 'traveler', 
        'ubereats', 'vehicle', 'workers', 'yelp'
    ],

    # Other Services (except Public Administration) (81)
    81: [
        'advocacy', 'association', 'automotive', 'beauty', 'business', 'care', 
        'civic', 'commercial', 'death', 'dry cleaning', 'drycleaning', 
        'electronic', 'equipment', 'giving', 'goods', 'grantmaking', 
        'household', 'households', 'industrial', 'labor', 'laundry', 
        'machinery', 'maintenance', 'nonprofit', 'organization', 
        'organizations', 'personal', 'personal services', 'pet', 'political', 
        'precision', 'private', 'professional', 'religious', 'repair', 'salon', 
        'social', 'veterinary'
    ],

    # Public Administration (92)
    92: [
        'administration', 'affairs', 'city', 'civic', 'community', 
        'compliance', 'county', 'economic', 'emergency', 'environmental', 
        'executive', 'federal', 'government', 'housing', 'human', 
        'international', 'justice', 'legislative', 'licensing', 'municipal', 
        'national', 'order', 'permits', 'planning', 'policy', 'programs', 
        'public', 'public safety', 'quality', 'regulation', 'research', 
        'resource', 'safety', 'security', 'social services', 'space', 'state', 
        'tax', 'technology', 'urban'
    ],

}