"""
Query GitHub Commit Search API for Claude Code commits.
Samples the 1st of each month from Nov 2024 to Mar 2026.

Usage:
  export GITHUB_TOKEN=ghp_your_token_here
  python gh-claude-activity.py
  python gh-claude-activity.py --alldays                # Every day, not just 1st of month
  python gh-claude-activity.py --coauthored-only        # Only "Co-authored-by: Claude"
  python gh-claude-activity.py --alldays --coauthored-only

You need a GitHub personal access token (classic) with no special scopes.
The commit search API is rate-limited to 30 requests/minute for authenticated users.
"""

import argparse
import requests
import time
import os
import json
from datetime import datetime, timedelta

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")

HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}
if GITHUB_TOKEN:
    HEADERS["Authorization"] = f"Bearer {GITHUB_TOKEN}"

SEARCH_URL = "https://api.github.com/search/commits"

# Dates to sample: 1st of each month
MONTHLY_DATES = [
    "2024-11-01",
    "2024-12-01",
    "2025-01-01",
    "2025-02-01",
    "2025-03-01",
    "2025-04-01",
    "2025-05-01",
    "2025-06-01",
    "2025-07-01",
    "2025-08-01",
    "2025-09-01",
    "2025-10-01",
    "2025-11-01",
    "2025-12-01",
    "2026-01-01",
    "2026-02-01",
    "2026-03-01",
]

# Search queries that identify Claude Code commits
ALL_QUERIES = [
    'committer-name:"Claude"',
    'author-name:"Claude"',
    '"Co-authored-by: Claude"',
    '"Generated by Claude"',
]

COAUTHORED_ONLY_QUERIES = [
    '"Co-authored-by: Claude"',
]


def generate_all_days(start="2025-02-01", end="2026-03-04"):
    """Generate every date from start to end (inclusive)."""
    dates = []
    current = datetime.strptime(start, "%Y-%m-%d")
    end_dt = datetime.strptime(end, "%Y-%m-%d")
    while current <= end_dt:
        dates.append(current.strftime("%Y-%m-%d"))
        current += timedelta(days=1)
    return dates


def search_commits(query, date):
    """Search commits for a specific query on a specific date. Returns total_count."""
    full_query = f"{query} committer-date:{date}"
    params = {"q": full_query, "per_page": 1}  # We only need the count

    try:
        resp = requests.get(SEARCH_URL, headers=HEADERS, params=params)

        if resp.status_code == 403:
            # Rate limited - wait and retry
            reset_time = int(resp.headers.get("X-RateLimit-Reset", 0))
            wait = max(reset_time - int(time.time()), 10)
            print(f"  Rate limited. Waiting {wait}s...")
            time.sleep(wait)
            return search_commits(query, date)

        if resp.status_code == 422:
            # Validation error - query might not be supported
            print(f"  Query not supported: {query}")
            return 0

        resp.raise_for_status()
        data = resp.json()
        return data.get("total_count", 0)

    except requests.exceptions.RequestException as e:
        print(f"  Error: {e}")
        return 0


def main():
    parser = argparse.ArgumentParser(description="Query GitHub for Claude Code commits")
    parser.add_argument("--alldays", action="store_true", help="Query every day, not just 1st of each month")
    parser.add_argument("--coauthored-only", action="store_true", help="Only search for 'Co-authored-by: Claude'")
    args = parser.parse_args()

    if not GITHUB_TOKEN:
        print("WARNING: No GITHUB_TOKEN set. You'll hit rate limits very quickly.")
        print("Set it with: export GITHUB_TOKEN=ghp_your_token_here\n")

    dates = generate_all_days() if args.alldays else MONTHLY_DATES
    queries = COAUTHORED_ONLY_QUERIES if args.coauthored_only else ALL_QUERIES

    print(f"Dates: {len(dates)} {'(all days)' if args.alldays else '(monthly)'}")
    print(f"Queries: {len(queries)} {'(co-authored only)' if args.coauthored_only else '(all)'}")

    results = []

    for date in dates:
        print(f"\n--- {date} ---")
        day_total = 0
        query_counts = {}

        for query in queries:
            count = search_commits(query, date)
            print(f"  {query}: {count}")
            query_counts[query] = count
            day_total += count
            time.sleep(2)  # Stay under rate limit

        # Note: there may be overlap between queries (same commit matching multiple patterns)
        # The total is an upper bound
        print(f"  TOTAL (may have duplicates): {day_total}")
        results.append({"date": date, "total": day_total, **query_counts})

    print("\n\n=== SUMMARY ===")
    print(f"{'Date':<15} {'Commits':>10}")
    print("-" * 27)
    for r in results:
        print(f"{r['date']:<15} {r['total']:>10}")

    # Save results
    output_path = "data/internal-cl/gh-claude-activity.json"
    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {output_path}")


if __name__ == "__main__":
    main()
